[build]
  publish = "."         # Loyihani joylashtirish katalogi
  command = ""          # Agar build komandasi yo‘q bo‘lsa, bo‘sh qoladi

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/main.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
